<div class="frame frame1">
    <div class="obiWan preload" data-source="{{root}}image/Old_Obi_Wan_128px_1082920_easyicon.net.svg">
        <div class="talkbubble">
            <div class="words"></div>
        </div>
    </div>
    <div class="door-wrapper">
        <div class="door-list">
            <div class="door-item">
                <div class="arrow-down preload" data-source="{{root}}image/Arrow_big_down_1197958_easyicon.net.svg"></div>
                <div class="cross-red preload" data-source="{{root}}image/cross_1187636_easyicon.net.svg"></div>
                <div class="door preload" data-source="{{root}}image/door_1204922_easyicon.net.svg"></div>
            </div>
            <div class="door-item">
                <div class="arrow-down preload" data-source="{{root}}image/Arrow_big_down_1197958_easyicon.net.svg"></div>
                <div class="cross-red preload" data-source="{{root}}image/cross_1187636_easyicon.net.svg"></div>
                <div class="door preload" data-source="{{root}}image/door_1204922_easyicon.net.svg"></div>
            </div>
            <div class="door-item">
                <div class="arrow-down preload" data-source="{{root}}image/Arrow_big_down_1197958_easyicon.net.svg"></div>
                <div class="cross-red preload" data-source="{{root}}image/cross_1187636_easyicon.net.svg"></div>
                <div class="door preload" data-source="{{root}}image/door_1204922_easyicon.net.svg"></div>
            </div>
        </div>
    </div>
</div>
