<div class="circle">
    <div class="game-number">
        <span>#{{index}}</span>
    </div>
</div>
<div class="frame-game-wrapper">
    <div class="frame-game-left frame-game-part">
        <ul class="options">
            <li>
                <span>A:&nbsp;&nbsp;</span>
                <span>xxxx</span>
            </li>
            <li>
                <span>B:&nbsp;&nbsp;</span>
                <span>xxxx</span>
            </li>
            <li>
                <span>C:&nbsp;&nbsp;</span>
                <span>xxxx</span>
            </li>
        </ul>
    </div>
    <div class="frame-game-right frame-game-part">
        <div class="frame-game-question">
            <span>xxx xxxx xxxx xxxx xxxxx xxxxxx</span>
        </div>
        <div class="divide-line"></div>
    </div>
    <div class="line line-top">
        <div class="bar"></div>
    </div>
    <div class="line line-right">
        <div class="bar"></div>
    </div>
    <div class="line line-left">
        <div class="bar"></div>
    </div>
    <div class="line line-bottom">
        <div class="bar"></div>
    </div>
</div>
<div class="page-back">
    <img src="./image/previous_256px_1139530_easyicon.net.png" alt=""/>
</div>
