<div class="frame-intro-item">
    <div class="frame-intro-item-wrapper">
        <div class="frame-intro-item-left">
            <div class="left-mask mask"></div>
            <img src="./image/trends.jpg" alt=""/>
            <div class="right-mask mask"></div>
        </div>
        <div class="frame-intro-item-right">
            <div class="info-contianer">
                <div class="category">
                    <span>{{category}}</span>
                </div>
                <div class="title">
                    <span>{{title}}</span>
                </div>
                <div class="sub-title">
                    <span>{{sub_title}}</span>
                </div>
            </div>
        </div>
        <div class="next-page">
            <img src="./image/next_128px_1139524_easyicon.net.png" alt="" />
        </div>
    </div>
</div>
